### PR TITLE
[JENKINS-26217] Enable support for HEAD (v2.5) Subversion plugin.

### PR DESCRIPTION
**Pull request by duttonw**
Have applied supplied patch to make svn-tag-plugin work with subversion plugin 2.5 so that people can use us subversion 1.8 with jenkins with this plugin

### CODE REVIEW

**Comment by daniel-beck** [comment]
What does this do that simply upgrading Jenkins itself and the Subversion plugin won't accomplish?

**Comment by duttonw** [comment]
Fixes 
java.lang.NoSuchMethodError:
hudson.scm.SubversionSCM.getRevisionFile(...)

Which now occurs with this plugin with 
latest Jenkins and latest subversion-plugin 2.5 when trying to auto tag on successful builds 

As per https://issues.jenkins-ci.org/browse/JENKINS-26217

**Comment by daniel-beck** [comment]
Right, API in Subversion plugin was changed and this just needs a recompile to pick up the new parameter types.

**Comment by cjhkramer** [comment]
Wouldn't mind seeing this one merged. Currently we're running on the hotfix release in the issue.

**Comment by psujeethkumar** [comment]
I I tried this plugin on jenkins V 1.597 subversion plugin v 2.5 and svn tag plugin 1.7 with this pull request change, but ended up with below exception:

ERROR: Publisher hudson.plugins.svn_tag.SvnTagPublisher aborted due to exception
java.lang.NoSuchMethodError: hudson.scm.SubversionSCM.getRevisionFile(Lhudson/model/AbstractBuild;)Ljava/io/File;
	at hudson.plugins.svn_tag.SvnTagPlugin.parseRevisionFile(SvnTagPlugin.java:242)
	at hudson.plugins.svn_tag.SvnTagPlugin.perform(SvnTagPlugin.java:97)
	at hudson.plugins.svn_tag.SvnTagPublisher.perform(SvnTagPublisher.java:79)
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
	at hudson.model.Build$BuildExecution.cleanUp(Build.java:192)
	at hudson.model.Run.execute(Run.java:1764)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)

**Comment by duttonw** [comment]
I've updated to the latest jenkins version, If building from source please try a 'mvn clean package' as it should not be causing NoSuchMethodError. or try the compiled version at https://issues.jenkins-ci.org/secure/attachment/28385/svn-tag.hpi

**Comment by psujeethkumar** [comment]
It works now, thank you !

File: pom.xml [hunk 1]
```diff
@@ -3,7 +3,7 @@
     <parent>
         <groupId>org.jenkins-ci.plugins</groupId>
         <artifactId>plugin</artifactId>
-        <version>1.424</version>
+        <version>1.597</version>
```
Comment (christ66) [inline pom.xml]: Do not use latest Jenkins version. Use the baseline LTS line (1.580).

**Comment by christ66** [comment]
@duttonw while this might fix the issue I believe it would be better to restore the method that was previously removed in the SubversionSCM class. I created https://github.com/jenkinsci/subversion-plugin/pull/108 to supersede this PR.

**Comment by christ66** [comment]
Closing this pull request as this was fixed upstream in https://github.com/jenkinsci/subversion-plugin/pull/108. This fix will be made available in the next release.
